### ISSUE TITLE
Avery labels have a blank line at the top

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#1]
I'm told they only start on the second line of labels.

See complaint at https://boardgamegeek.com/article/18964732#18964732 and follow-ups below it.

**Comment by wvoigt** [comment]
I *think* this can be fixed by changing the label's
minmarginheight = 1.17 * cm
from 1.27 * cm.  That is the number that is needed to get exactly the 20 rows of labels.  However, it will have the effect of moving all the labels down 0.1 * cm.

I don't have these labels to check out to see if this change causes vertical alignment problems with the labels.  So I will not submit a patch at this time.

**Comment by wvoigt** [comment]
I stand corrected.  The minmarginheight should stay at 1.27 * cm, since the margin really is one label height.  I believe this can be fixed as part of issue #23.

**Comment by sumpfork** [comment]
Hopefully fixed by now that #23 is fixed by 0c1860266c9c2d2b8c76a11640bc678a78dd74a5
