### ISSUE TITLE
Web generator does not generate Dominion or Intrigue expansions 

### ISSUE THREAD

**Issue by wvoigt** [sumpfork/dominiontabs#157]
With the new release, I can't generate any Dominion or Intrigue sets.
I suspect the spaces in the names are throwing it off.

**Comment by sumpfork** [comment]
Right, I forgot to update how I pass in the expansion names given the changes in the library.

**Comment by sumpfork** [comment]
The problems were that
1) Cleaning up the options (e.g. lowercasing the expansions) was part of parsing the options, but the generator creates the options from the form rather than parsing a command line, so they weren't being cleaned in the same way. I separated cleaning as a second step after parsing and am calling that from the generator now.
2) The expansions need to be a list of lists of strings, not a list of strings.

Fixed with a092fca9e673903e770bd71ceb3410166112ca74 and https://github.com/sumpfork/bgtools_web/commit/76782c337bbdd6c96f4952d504ae82b1710e44d7.
