### ISSUE TITLE
Promo Expansion Symbol

### ISSUE THREAD

**Issue by TMDaines** [sumpfork/dominiontabs#247]
All the currently printed promo cards have the same symbol (the flag), even the older ones have now had a second printing with this symbol. Could the promo tabs be updated to all have the correct, current expansion symbol?

**Comment by nickv2002** [comment]
My cards have the old symbol so I'd prefer those icons. (I think the original promo icons were pretty neat and expressive, soI miss the fact that they don't make them any more.)

So perhaps we could make it an option at some point. @TMDaines if you want to duplicate the result beforehand without much coding you could always just copy the flag icon image to have the same name as all the other icons and build your own. (I know it's not _easy_ though, because you still have to run the code locally instead of using the awesome web version.)

**Comment by sumpfork** [comment]
I'd rather keep the unique symbols, too. If somebody wants to make a pull request to optionally standardize them to the new flag symbol, I'll be happy to accept it.

**Comment by TMDaines** [comment]
If I could do this, I would, but I need to teach myself. Would love to have this option.
