### ISSUE TITLE
Generated file size is too big

### ISSUE THREAD

**Issue by sumpfork** [sumpfork/dominiontabs#443]
After @bszonye's changes to improve the banner images the filesize for a complete divider file jumped from <5mb to 24mb. That's ok for local printing, but because of the way the online generator works I'm limited to a 6mb response size (imposed by AWS lambda), so even generating a single expansion throws an error with the new version.

A couple of options I can think of:
- scale the images down to a size closer to the original one (sad to lose the print quality)
- have two versions and an option to switch to smaller sizes for the online generator, but still distribute the bigger ones for local script usage
- Instead of putting the pdf in the response and having the browser download it, put it on S3 and provide a download link instead
- The above S3 solution, but combine with the two size solution and generate both, return the smaller, also point to the bigger
- The preview also is failing. It only generates the first 2 pages, so I'll have to look into why even that size is too big. I think it's because we actually spec the whole file and then later limit it to two pages?

I don't have time to rework the backend to not be Lambda-based and want to keep it this way for cost reasons anyway.

**Comment by sumpfork** [comment]
I guess another option is to generate jpgs for them to use for the online version. I believe reportlab has more direct jpg support and the file sizes would be smaller at the loss of some quality.

**Comment by bszonye** [comment]
Oh no!

JPEGs are significantly smaller, but they don't support transparency. That would be a problem for things like the icon overlays, and it would also interfere with the black tabs option. It's too bad, because JPEGs can offer a significant space reduction with nearly imperceptible loss of quality. For example, I used the Photos app in Windows to convert `action.png` (1.37 MB) to `action.jpg` (0.22 MB), and Photoshop lets you tune the quality/size tradeoff however you like.

The new images are 600 dpi for high-resolution printing, but I agree that it would be a reasonable compromise to use a lower resolution for the online generator. Instead of creating a second set of images, what about dynamically rescaling the current images? I suspect that PIL can do it if reportlab can't.

**Comment by bszonye** [comment]
OK, I have a way to dynamically resample the images. I inserted this code:
```
              rescale = (300 / 1200)  # TODO: make this an option
              if rescale != 1.0:  # resample
                  imgObj = Image.open(imgToDraw)
                  x, y = imgObj.size
                  imgObj = imgObj.resize(
                      (round(rescale * x), round(rescale * y)),
                      Image.ANTIALIAS,
                  )
                  imageBytes = BytesIO()
                  imgObj.save(imageBytes, "PNG")
                  imageBytes.seek(0)
                  imgToDraw = ImageReader(imageBytes)
```
right before the banner rendering code here:
https://github.com/sumpfork/dominiontabs/blob/master/src/domdiv/draw.py#L1541-L1550

This resamples the banners from 1200 dpi to the 300 dpi of the older images. It works, but there's a tradeoff. The generated PDFs are much smaller (about 1/10 the original size) but the generation takes _much_ longer to run (about 10x time). Partly that's because it's resampling the same image over and over; I can probably address that with memoization.

I'll put together a PR. For the CLI, I'm thinking this can be a new `--resample=DPI` option, e.g. `--resample=300` to get the older resolution.

By the way, the new images look great even at much lower resolution:

![image](https://user-images.githubusercontent.com/5016349/211223429-03ad1666-2c83-47b1-8a03-4f4f9596487d.png)

You can see some aliasing around the edges, so you know that it's working 😹 but it's still significantly smoother than the old images.

**Comment by bszonye** [comment]
I moved the opacity/resampling code out to a `@staticmethod @functools.cache` method, which solved the speed performance problems. Putting together a hotfix PR for you.

**Comment by sumpfork** [comment]
Awesome, thanks.

**Comment by bszonye** [comment]
The solution was a bit more complicated because I had to make sure that it wouldn't pixelate the landscape and Curse banners. I ended up writing it so that it calculates the maximum artwork area given the DPI, and then shrinks the art to fit if it's bigger. That should minimize any distortion. If you set `--tab-artwork-resolution=300` in the online generator, you should get file sizes comparable to the old version again.
